### ISSUE TITLE
Slash Swapper and Smart Chat Input Colour compatibility?

### ISSUE THREAD

**Issue by verafeiyd** [MarbleTurtle/Color-Coordinator#14] opened 2023-11-15 15:18 UTC
I love this plugin, but with Slash Swapper to move friends chat and guild chat, this seems to have the input colour swapped, any chance we could get an override option for this?

**Comment by ririshi** [comment] 2023-11-15 15:42
Isn't this a duplicate of #11?

**Comment by verafeiyd** [comment] 2023-11-15 17:47
11 is a bug between the gc not swapping correctly, this is a bug for chat recolouring not swapping correctly

**Comment by verafeiyd** [comment] 2023-11-15 17:48
i use green for fc, teal for cc, with this plugin and slash swapper one / for the input goes green but goes to my cc, and fc is teal with // but goes to fc

**Comment by ririshi** [comment] 2023-11-15 18:45
The issue I mentioned also states that Smart Chat Input Color isn't correctly coloring the input when Slash Swapper is active. The comment about the gc is just an addition to help implement the cross-plugin support.

I'm currently not playing the game, but I am working on a new version which supports Slash Swapper, including its configuration and its bug behaviour.

**Comment by verafeiyd** [comment] 2023-11-15 20:53
well well, thank you very much, i appreciate the quick response and i apologize for my misunderstanding <3 love the plugin, thanks again!

**Comment by ririshi** [comment] 2023-11-21 06:47
New version is almost ready to go. I will create a PR with the plugin hub soon, so it should be ready for use as soon as that one gets merged.

**Comment by ririshi** [comment] 2023-11-22 17:15
Fixed in 1.5.0! Should appear in plugin hub when the PR gets merged by the kind folks there.

**Closed as completed by ririshi** 2023-11-22 17:15 UTC
